- name: loops
  hosts: local
  connection: local
  tasks:
  - name: print names
    ansible.builtin.debug:
      msg: "Hello {{ item }}"  # access by keyword {{item}}
    loop:
    - Ramesh
    - Suresh
    - Hareesh